using Microsoft.Extensions.Logging;

using Newsroom.Core.Ai;
using Newsroom.Core.Drafting;

namespace Newsroom.Infrastructure.Images;

/// <summary>
/// The draft pipeline's single cover-image seam (docs/05-integrations/images.md, ADR-0011),
/// called before the draft goes to Telegram review: AI generation first (tier 3 — a unique
/// on-topic illustration from the article's own details), stock search (tier 2 — Pexels,
/// Pixabay) as the fallback whenever the generator is unconfigured, out of daily budget
/// (Ai:Stages:Image:DailyRequestBudget caps the Cloudflare free tier), or fails for any
/// reason. Fallback failures follow the existing contract: an empty result just sends the
/// draft to review without image suggestions.
/// </summary>
public sealed class FeaturedImageService(
    IAiImageGenerator generator,
    ImageSuggestionService stockSuggestions,
    IAiBudget budget,
    ILogger<FeaturedImageService> logger)
{
    /// <summary>nw_CostLedger stage of one generation request (ADR-0010 metering).</summary>
    public const string Stage = "Image";

    public async Task<IReadOnlyList<ImageCandidate>> GetCandidatesAsync(
        DraftContent content, CancellationToken ct)
    {
        if (!generator.IsConfigured)
            return await stockSuggestions.SuggestAsync(content.ImageSearchQueries, ct);

        try
        {
            if (!await budget.TryReserveAsync(Stage, ct))
            {
                logger.LogWarning(
                    "Daily AI request budget for stage {Stage} exhausted; using stock image suggestions",
                    Stage);
                return await stockSuggestions.SuggestAsync(content.ImageSearchQueries, ct);
            }

            var result = await generator.GenerateAsync(content, ct);
            await budget.RecordAsync(Stage, result.Usage, ct);
            logger.LogInformation("🎨 Cover image generated by {Provider}: {Path}",
                generator.Name, result.Image.Url);
            return [result.Image];
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            logger.LogWarning(ex,
                "AI cover-image generation failed; falling back to the stock providers");
            return await stockSuggestions.SuggestAsync(content.ImageSearchQueries, ct);
        }
    }
}
